import frappe
from frappe.utils.pdf import get_pdf
from frappe.utils import now_datetime, format_datetime


CHIP_COLORS = {
    "Open": ("#eef4ff", "#3b6fd6"),
    "Working": ("#fff6e5", "#c98a1a"),
    "Completed": ("#eaf8ef", "#2e9e5b"),
    "Closed": ("#eaf8ef", "#2e9e5b"),
    "Cancelled": ("#f4f4f4", "#888888"),
    "High": ("#fdecec", "#d9534f"),
    "Emergency": ("#fdecec", "#d9534f"),
    "Urgent": ("#fdecec", "#d9534f"),
    "Medium": ("#fff6e5", "#c98a1a"),
    "Low": ("#eaf8ef", "#2e9e5b"),
    "Paid": ("#eaf8ef", "#2e9e5b"),
    "Pending": ("#fff6e5", "#c98a1a"),
    "Overdue": ("#fdecec", "#d9534f"),
}

KPI_COLORS = ["#eef4ff", "#eaf8ef", "#fdecec", "#fff6e5", "#f4f4f4"]
KPI_TEXT_COLORS = ["#3b6fd6", "#2e9e5b", "#d9534f", "#c98a1a", "#555555"]


def _chip(value):
    if value is None or value == "":
        return ""
    bg, color = CHIP_COLORS.get(str(value), ("#f4f4f4", "#555555"))
    return f'<span style="background:{bg}; color:{color}; padding:3px 10px; border-radius:12px; font-size:11px; font-weight:600;">{value}</span>'


def _format_cell(value, fieldtype):
    if value is None:
        return ""
    if fieldtype == "Check":
        return "Yes" if value else ""
    return str(value)

def _build_kpi_html(report_summary):
    if not report_summary:
        return ""
    cells = ""
    for i, kpi in enumerate(report_summary):
        bg = KPI_COLORS[i % len(KPI_COLORS)]
        color = KPI_TEXT_COLORS[i % len(KPI_TEXT_COLORS)]
        cells += f"""
        <td style="background:{bg}; padding:16px; text-align:center; border-radius:4px;">
            <div style="font-size:24px; font-weight:700; color:{color};">{kpi.get("value")}</div>
            <div style="font-size:11px; color:#555; text-transform:uppercase; letter-spacing:0.5px; margin-top:4px;">{kpi.get("label")}</div>
        </td>
        <td style="width:8px;"></td>
        """
    return f'''
    <table style="width:100%; border-collapse:separate; border-spacing:0; margin-top:16px;">
        <tr>{cells}</tr>
    </table>
    '''


def _build_filter_summary_html(filters, filter_defs):
    if not filters:
        return ""
    items = []
    for f in filter_defs:
        fieldname = f.get("fieldname")
        value = filters.get(fieldname)
        if value:
            items.append((f.get("label", fieldname), value))
    if not items:
        return ""

    cols_html = ""
    for label, value in items:
        cols_html += f"""
        <div style="margin-right:32px;">
            <div style="font-size:10px; color:#9fb0c3; text-transform:uppercase; letter-spacing:0.5px;">{label}</div>
            <div style="font-size:13px; color:#fff; margin-top:2px;">{value}</div>
        </div>
        """
    return cols_html


def render_report_pdf(report_name, filters=None):
    filters = filters or {}
    report = frappe.get_doc("Report", report_name)

    columns, data, message, chart, report_summary = (list(report.execute_module(filters)) + [None] * 5)[:5]

    filter_summary_html = _build_filter_summary_html(filters, report.filters)
    generated_html = f"""
    <div style="margin-right:0;">
        <div style="font-size:10px; color:#9fb0c3; text-transform:uppercase; letter-spacing:0.5px;">Generated</div>
        <div style="font-size:13px; color:#fff; margin-top:2px;">{format_datetime(now_datetime(), "dd MMM yyyy, HH:mm")}</div>
    </div>
    """

    table_html = _build_table_html(columns, data)
    kpi_html = _build_kpi_html(report_summary)

    html = f"""
    <html>
    <head>
        <style>
            @page {{ size: A4 landscape; margin: 20px; }}
            body {{ font-family: Arial, sans-serif; margin:0; padding:0; }}
        </style>
    </head>
    <body>
        <div style="background:#2d3e50; padding:20px 24px; border-radius:6px 6px 0 0;">
            <div style="display:flex; justify-content:space-between; align-items:flex-start;">
                <div>
                    <div style="font-size:22px; font-weight:700; color:#fff;">{report.report_name}</div>
                </div>
                <div style="display:flex;">
                    {filter_summary_html}
                    {generated_html}
                </div>
            </div>
        </div>
        {table_html}
        {kpi_html}
        <div style="margin-top:20px; padding-top:8px; border-top:1px solid #eee; display:flex; justify-content:space-between; font-size:10px; color:#999;">
            <div>Implementor App</div>
            <div>Generated by {frappe.session.user}</div>
        </div>
    </body>
    </html>
    """

    return get_pdf(html, options={
    "page-size": "A4",
    "orientation": "Landscape",
    "margin-top": "10mm",
    "margin-bottom": "10mm",
    "margin-left": "8mm",
    "margin-right": "8mm",
})

def _build_table_html(columns, data):
    visible_columns = [c for c in columns if c.get("width", 100) != 0]

    header_html = "".join(
        f'<th style="padding:5px 6px; text-align:left; font-size:10px;">{c["label"]}</th>'
        for c in visible_columns
    )

    chip_fields = {"status", "priority", "payment_status", "completion_status"}

    rows_html = ""
    for row in data:
        cells = ""
        for c in visible_columns:
            val = row.get(c["fieldname"])
            if c["fieldname"] in chip_fields:
                cells += f'<td style="padding:5px 6px; font-size:10px;">{_chip(val)}</td>'
            else:
                cells += f'<td style="padding:5px 6px; font-size:10px;">{_format_cell(val, c.get("fieldtype"))}</td>'
        rows_html += f'<tr style="border-bottom:1px solid #eee;">{cells}</tr>'

    return f"""
    <table style="width:100%; border-collapse:collapse; font-size:10px; table-layout:auto;">
        <thead>
            <tr style="background:#2d3e50; color:#fff;">{header_html}</tr>
        </thead>
        <tbody>{rows_html}</tbody>
    </table>
    """
@frappe.whitelist()
def download_report_pdf(report_name, filters=None):
    filters = frappe.parse_json(filters) if isinstance(filters, str) else (filters or {})
    pdf_content = render_report_pdf(report_name, filters)
    frappe.local.response.filename = f"{report_name}.pdf"
    frappe.local.response.filecontent = pdf_content
    frappe.local.response.type = "download"